### ISSUE TITLE
Task `AboveBelow3` size mismatch

### ISSUE THREAD

**Issue by neoneye** [victorvikram/ConceptARC#4]
The json file is here:
https://github.com/victorvikram/ConceptARC/blob/main/corpus/AboveBelow/AboveBelow3.json

All the pairs have same size for input and output. Except one pair where the size differs by 1 column and 1 row.
![Screenshot 2023-06-19 at 23 25 07](https://github.com/victorvikram/ConceptARC/assets/147971/e8e8073a-afe4-46a1-b6d8-82ad5fdc7386)

**Comment by Le-Gris** [comment]
I was about to raise an issue related to this as well, it seems that there is a mistake for the AboveBelow3 task.
